apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validations.codetriarii.org
webhooks:
  - name: pods.validations.codetriarii.org
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
        scope: Namespaced
    clientConfig:
      service:
        namespace: demo
        name: uvicorn-service
        path: "/validate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURiVENDQWxXZ0F3SUJBZ0lVYk5HNWllNXJKWDBHTmtELzdnaERCYWR0SnFVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0pqRWtNQ0lHQTFVRUF3d2JkWFpwWTI5eWJpMXpaWEoyYVdObExtUmxiVzh1YzNaaklFTkJNQjRYRFRJMApNRFF5TlRFMk1qUTFNVm9YRFRJMU1EUXlOVEUyTWpRMU1Wb3dKakVrTUNJR0ExVUVBd3diZFhacFkyOXliaTF6ClpYSjJhV05sTG1SbGJXOHVjM1pqSUVOQk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0MKQVFFQXc4c2txaU1qZ0FvOC9ZOFFaWHBNZFlDS3M1RzZiem1oL1BkSXN1d0lZUCtGZ0pNWm9NRmFWT2EyQWd1QwpLNTNad1FqaExiVzRwci9OeEs1SCtZeGxVTkZnenhab2FQUUlRTlI2d2huK1ZzVzRseC9DdjdvZUI2eGxLVHMxCnRsaVliZHNIeGtPUDFoelp4eFRMdmdxRXU1WVIxQ3g3eWtLalVxTDdxaGZkVEdlRDJTSnpoOG5PUzd3MERKdmUKNnRNQjJzenFjVWh3ZE44ZjFINmdBTU5UQ3JQcDVBeG1telhZVGRKRGw5aG03K0lWc2Q3WERlMEhpYVU3SlBUawpPdVM2OEgrN0toNmp0bnY2ZFJBN3A1WW4vTEpXVk5QQTdwYURmem0rUVlnck5MY0VkZGNiQThYbkNkVUJCWXAwCm9qTGNna0pFanhQaEZqeEZKbTE4MzJ1Y1R3SURBUUFCbzRHU01JR1BNQjBHQTFVZERnUVdCQlQ2NmJESFFYZmgKRGgrc3lsdCtqOHJURGNpL2JUQWZCZ05WSFNNRUdEQVdnQlQ2NmJESFFYZmhEaCtzeWx0K2o4clREY2kvYlRBcApCZ05WSFJFRUlqQWdnaGgxZG1samIzSnVMWE5sY25acFkyVXVaR1Z0Ynk1emRtT0hCSDhBQUFFd0RnWURWUjBQCkFRSC9CQVFEQWdLRU1CSUdBMVVkRXdFQi93UUlNQVlCQWY4Q0FRQXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUIKQUhFclRDdW5pcjd1VmhQeTlCbVZyMGlOK1RacU1sVXA0dDNla1hsQk1wZTBtSUNSK1E4VEVhOGlIMnhISlJvWgpJWmlUNDJGSGtFaVpSbE5HYXFycENjZUJvaGVZVHA5RHl1NUFKTHlwdHY2WWYvWnFZenNKVDRCTUNGaXkrRmRjCnIyTWM2VFBDd0U3SW9TWDgvdmRnQ1lxMHpSTW5NU2NNNkJHMThQVHFqOW9kei9ITWpESTdib2Q3SGtlOWpoY1YKZzJBMzgzVHprcW9wU0duL0UwYy9KSFVOUFlZeTV3azZ0RUJiU1lXNlZZYlFZUGRmUGljUzdZeGtVbm5JK20ybgpnWHltb2MwcDRaT0JIOGxTT09MWEdWbkV5M0doRDNTM1QrdjN0eHl1eGdYeWREcE5UZEFNRmxpQU00ZWJLOWJhCklxNXJBNFJzd0YzcTRzbkNZazNlVXYwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    admissionReviewVersions:
      - v1
    sideEffects: None
    timeoutSeconds: 5
